# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='recipemeal',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='recipemeal',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='meal',
            field=models.TextField(blank=True, choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('dessert', 'Dessert'), ('snackApp', 'Snack or Appetizer'), ('beverage', 'Beverage')], null=True),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
        migrations.DeleteModel(
            name='RecipeIngredient',
        ),
        migrations.DeleteModel(
            name='RecipeMeal',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
