# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20170405_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.TextField(blank=True, choices=[('cup', 'Cups'), ('tsp', 'Teaspoon'), ('tbsp', 'Tablespoon'), ('oz', 'Ounces'), ('count', '(No Units)')], null=True),
        ),
        migrations.AlterField(
            model_name='recipemeal',
            name='meal',
            field=models.TextField(blank=True, choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('dessert', 'Dessert'), ('snackApp', 'Snack or Appetizer'), ('beverage', 'Beverage')], null=True),
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
