# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20170405_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cook_time',
            field=models.TextField(blank=True, null=True),
        ),
    ]
